<template>
  <component 
    :is="iconComponent" 
    v-bind="$attrs"
  />
</template>

<script setup lang="ts">
import { 
  ArrowRight, 
  ExternalLink, 
  Mail, 
  Phone, 
  MapPin, 
  Calendar,
  Clock,
  User,
  Users,
  Star,
  Heart,
  Check,
  X,
  Plus,
  Minus,
  Search,
  Menu,
  Home,
  Settings,
  Shield,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Play,
  Pause,
  Download,
  Upload,
  Share,
  Copy,
  Edit,
  Trash,
  Save,
  Bookmark,
  Tag,
  Globe,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Volume,
  VolumeX,
  Camera,
  Image,
  Video,
  Music,
  FileText,
  File,
  Folder,
  Archive,
  Package,
  Box,
  Truck,
  Car,
  Plane,
  Ship,
  Train,
  Bike,
  Coffee,
  Pizza,
  Gift,
  Zap,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  Award,
  Target,
  Flag,
  Rocket,
  Lightbulb,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Bell,
  BellOff,
  Smartphone,
  Laptop,
  Monitor,
  Tablet,
  Watch,
  Headphones,
  Mic,
  MicOff,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle
} from 'lucide-vue-next'

interface Props {
  name: string
}

const props = defineProps<Props>()

// Маппинг названий иконок на компоненты
const iconMap = {
  'arrow-right': ArrowRight,
  'external-link': ExternalLink,
  'mail': Mail,
  'phone': Phone,
  'map-pin': MapPin,
  'calendar': Calendar,
  'clock': Clock,
  'user': User,
  'users': Users,
  'star': Star,
  'heart': Heart,
  'check': Check,
  'x': X,
  'plus': Plus,
  'minus': Minus,
  'search': Search,
  'menu': Menu,
  'home': Home,
  'settings': Settings,
  'shield': Shield,
  'lock': Lock,
  'unlock': Unlock,
  'eye': Eye,
  'eye-off': EyeOff,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'play': Play,
  'pause': Pause,
  'download': Download,
  'upload': Upload,
  'share': Share,
  'copy': Copy,
  'edit': Edit,
  'trash': Trash,
  'save': Save,
  'bookmark': Bookmark,
  'tag': Tag,
  'globe': Globe,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'battery': Battery,
  'battery-low': BatteryLow,
  'volume': Volume,
  'volume-x': VolumeX,
  'camera': Camera,
  'image': Image,
  'video': Video,
  'music': Music,
  'file-text': FileText,
  'file': File,
  'folder': Folder,
  'archive': Archive,
  'package': Package,
  'box': Box,
  'truck': Truck,
  'car': Car,
  'plane': Plane,
  'ship': Ship,
  'train': Train,
  'bike': Bike,
  'coffee': Coffee,
  'pizza': Pizza,
  'gift': Gift,
  'zap': Zap,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'award': Award,
  'target': Target,
  'flag': Flag,
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'megaphone': Megaphone,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'bell': Bell,
  'bell-off': BellOff,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'monitor': Monitor,
  'tablet': Tablet,
  'watch': Watch,
  'headphones': Headphones,
  'mic': Mic,
  'mic-off': MicOff,
  'help-circle': HelpCircle,
  'info': Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
}

const iconComponent = computed(() => {
  return iconMap[props.name] || HelpCircle
})
</script>
